"""subscribers: add name and comment

Revision ID: 09c5b62210f8
Revises: b6264cc54922
Create Date: 2025-10-13 22:27:33.269208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09c5b62210f8'
down_revision = 'b6264cc54922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('comment', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriber', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
