"""list: add avoid_duplicates setting

Revision ID: 0d19dc3b6347
Revises: cd01cdfd5ead
Create Date: 2025-11-13 16:35:19.840282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d19dc3b6347'
down_revision = 'cd01cdfd5ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avoid_duplicates', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('avoid_duplicates')

    # ### end Alembic commands ###
