"""message: add bounce_info column

Revision ID: 2cb6c660beee
Revises: a35bd3d394bf
Create Date: 2025-11-10 20:20:13.430473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb6c660beee'
down_revision = 'a35bd3d394bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bounce_info', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('bounce_info')

    # ### end Alembic commands ###
