"""list: add allowed senders

Revision ID: 373e20626e35
Revises: 6ae40f033710
Create Date: 2025-10-14 15:15:40.613365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373e20626e35'
down_revision = '6ae40f033710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allowed_sender')
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowed_senders', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('allowed_senders')

    op.create_table('allowed_sender',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('list_id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
