"""list: add only_subscribers_send

Revision ID: 78eb159226e6
Revises: 373e20626e35
Create Date: 2025-10-14 15:30:59.810888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78eb159226e6'
down_revision = '373e20626e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('only_subscribers_send', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('only_subscribers_send')

    # ### end Alembic commands ###
