"""list: add sender authentication passwords

Revision ID: 0d9ddee274ff
Revises: 6c835de41e89
Create Date: 2025-11-10 17:29:37.883392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d9ddee274ff'
down_revision = '6c835de41e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_auth', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('sender_auth')

    # ### end Alembic commands ###
