"""change nullables

Revision ID: 13cf2ed28421
Revises: 0d19dc3b6347
Create Date: 2025-11-14 22:24:50.771781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cf2ed28421'
down_revision = '0d19dc3b6347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('message_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('headers',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('headers',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('message_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
