"""list: add from_addr_setting

Revision ID: 7e6ba9b0ffe1
Revises: 2f9a173728b0
Create Date: 2025-12-04 17:29:55.966298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6ba9b0ffe1'
down_revision = '2f9a173728b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_addr_setting', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('from_addr_setting')

    # ### end Alembic commands ###
