"""list: add from settings for outside senders

Revision ID: 88c21e3e1c3b
Revises: 0df3b2586a2c
Create Date: 2025-12-05 13:21:11.825289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88c21e3e1c3b'
down_revision = '0df3b2586a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_addr_mode_outside', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('from_addr_custom_outside', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('list', schema=None) as batch_op:
        batch_op.drop_column('from_addr_custom_outside')
        batch_op.drop_column('from_addr_mode_outside')

    # ### end Alembic commands ###
