"""message: bounce_info -> error_info

Revision ID: cd01cdfd5ead
Revises: 2cb6c660beee
Create Date: 2025-11-10 21:37:34.570285

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'cd01cdfd5ead'
down_revision = '2cb6c660beee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_info', sa.JSON(), nullable=True))
        batch_op.drop_column('bounce_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bounce_info', sqlite.JSON(), nullable=True))
        batch_op.drop_column('error_info')

    # ### end Alembic commands ###
